### ISSUE TITLE
How to restore the permission settings in my account?

### ISSUE THREAD

**Issue by iceworlder** [bitshares/bitshares.github.io-old#117] opened 2018-02-23 08:31 UTC
Yesterday I changed the active and owner permissions by adding my account name to the list , and modified the weight and threshold like below:

![active](https://user-images.githubusercontent.com/31835139/36583673-a9085220-18b1-11e8-911a-12f6fefb5b7f.JPG)

![owner](https://user-images.githubusercontent.com/31835139/36583656-988c3010-18b1-11e8-88fa-b6fafa68b63a.JPG)

After saving these changes, I found that I cannot buy or sell anything, which showed: missing required active authority: Missing Active Authority 1.2.xxxxxx(my account ID).
So I intended to restore the original permission settings, but all attempts failed, it just showed the msg above.
Maybe the account name and the public key actually are the same thing, so my operations misleaded the system?
I'm so confuesd that how can i remove my account name from these permissions?
thx!

**Comment by abitmore** [comment] 2018-02-23 13:10
Duplicate of https://github.com/bitshares/bitshares-core/issues/269.

The account is effectively locked so far. Please store your original keys or password safely, in the future you may need them to recover the account.

**Closed as completed by abitmore** 2018-02-23 13:10 UTC

**Comment by iceworlder** [comment] 2018-02-23 14:08
Thanks for your attention @abitmore 
Waiting for your good news !
BTS account: bcbwbrldbr
